import api from './api';
export default {
  dashboard: () => api.get('/audit/dashboard'),
  recordAudit: (data) => api.post('/audit/audit', data),
  audit: (params) => api.get('/audit/audit', { params }),
  getAudit: (id) => api.get(`/audit/audit/${id}`),
  auditStats: (hours) => api.get('/audit/audit/stats', { params: { hours } }),
  checks: (framework, status) => api.get('/audit/checks', { params: { framework, status } }),
  getCheck: (id) => api.get(`/audit/checks/${id}`),
  updateCheck: (id, data) => api.patch(`/audit/checks/${id}`, data),
  runCheck: (id) => api.post(`/audit/checks/${id}/run`),
  runAllChecks: (framework) => api.post('/audit/checks/run-all', null, { params: { framework } }),
  generateReport: (data) => api.post('/audit/reports', data),
  reports: (framework) => api.get('/audit/reports', { params: { framework } }),
  getReport: (id) => api.get(`/audit/reports/${id}`),
  policies: (framework) => api.get('/audit/policies', { params: { framework } }),
  createPolicy: (data) => api.post('/audit/policies', data),
  getPolicy: (id) => api.get(`/audit/policies/${id}`),
  updatePolicy: (id, data) => api.patch(`/audit/policies/${id}`, data),
  deletePolicy: (id) => api.delete(`/audit/policies/${id}`),
  recordViolation: (id) => api.post(`/audit/policies/${id}/violation`),
  risks: (status, level) => api.get('/audit/risks', { params: { status, risk_level: level } }),
  createRisk: (data) => api.post('/audit/risks', data),
  getRisk: (id) => api.get(`/audit/risks/${id}`),
  updateRisk: (id, data) => api.patch(`/audit/risks/${id}`, data),
  deleteRisk: (id) => api.delete(`/audit/risks/${id}`),
  frameworks: () => api.get('/audit/frameworks'),
  startMonitoring: (interval) => api.post('/audit/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/audit/monitoring/stop'),
  monitoringStatus: () => api.get('/audit/monitoring/status'),
};
