import api from './api';
export default {
  dashboard: () => api.get('/bridge/dashboard'),
  health: () => api.get('/bridge/health'),
  createTransfer: (data) => api.post('/bridge/transfers', data),
  listTransfers: (params) => api.get('/bridge/transfers', { params }),
  getTransfer: (id) => api.get(`/bridge/transfers/${id}`),
  validateTransfer: (id, data) => api.post(`/bridge/transfers/${id}/validate`, data),
  executeTransfer: (id, txHash, blockHeight) => api.post(`/bridge/transfers/${id}/execute`, null, { params: { tx_hash_target: txHash, block_height_target: blockHeight } }),
  failTransfer: (id, error) => api.post(`/bridge/transfers/${id}/fail`, null, { params: { error } }),
  refundTransfer: (id) => api.post(`/bridge/transfers/${id}/refund`),
  transferStats: () => api.get('/bridge/transfers/stats'),
  registerRelayer: (data) => api.post('/bridge/relayers', data),
  listRelayers: (active) => api.get('/bridge/relayers', { params: { active_only: active } }),
  getRelayer: (id) => api.get(`/bridge/relayers/${id}`),
  activateRelayer: (id) => api.post(`/bridge/relayers/${id}/activate`),
  removeRelayer: (id) => api.delete(`/bridge/relayers/${id}`),
  createAlert: (data) => api.post('/bridge/alerts', data),
  listAlerts: (triggered) => api.get('/bridge/alerts', { params: { triggered } }),
  deleteAlert: (id) => api.delete(`/bridge/alerts/${id}`),
  resetAlert: (id) => api.post(`/bridge/alerts/${id}/reset`),
  startMonitoring: (interval) => api.post('/bridge/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/bridge/monitoring/stop'),
  monitoringStatus: () => api.get('/bridge/monitoring/status'),
};
