import api from './api';
export default {
  dashboard: () => api.get('/community/dashboard'),
  feedback: (params) => api.get('/community/feedback', { params }),
  feedbackStats: () => api.get('/community/feedback/stats'),
  submitFeedback: (data) => api.post('/community/feedback', data),
  getFeedback: (id) => api.get(`/community/feedback/${id}`),
  updateFeedbackStatus: (id, data) => api.patch(`/community/feedback/${id}/status`, data),
  voteFeedback: (id) => api.post(`/community/feedback/${id}/vote`),
  features: (params) => api.get('/community/features', { params }),
  createFeature: (data) => api.post('/community/features', data),
  getFeature: (id) => api.get(`/community/features/${id}`),
  voteFeature: (id, voter) => api.post(`/community/features/${id}/vote`, { voter }),
  updateFeatureStatus: (id, data) => api.patch(`/community/features/${id}/status`, data),
  addComment: (id, data) => api.post(`/community/features/${id}/comments`, data),
  members: (limit) => api.get('/community/members', { params: { limit } }),
  getMember: (addr) => api.get(`/community/members/${addr}`),
  registerMember: (data) => api.post('/community/members', data),
  awardBadge: (addr, type) => api.post(`/community/members/${addr}/badge/${type}`),
  leaderboard: (limit) => api.get('/community/leaderboard', { params: { limit } }),
  events: (params) => api.get('/community/events', { params }),
  createEvent: (data) => api.post('/community/events', data),
  getEvent: (id) => api.get(`/community/events/${id}`),
  registerForEvent: (id, addr) => api.post(`/community/events/${id}/register`, { address: addr }),
  badges: () => api.get('/community/badges'),
  usability: () => api.get('/community/usability'),
  usabilitySummary: () => api.get('/community/usability/summary'),
};
