import api from './api';
export default {
  dashboard: () => api.get('/cross-chain/dashboard'),
  stats: () => api.get('/cross-chain/stats'),
  transfers: (params) => api.get('/cross-chain/transfers', { params }),
  transfer: (id) => api.get(`/cross-chain/transfers/${id}`),
  recordTransfer: (data) => api.post('/cross-chain/transfers', data),
  chains: () => api.get('/cross-chain/chains'),
  chainMetrics: () => api.get('/cross-chain/chains/metrics'),
  chainMetric: (chain) => api.get(`/cross-chain/chains/${chain}/metrics`),
  compareChains: (chains) => api.get('/cross-chain/chains/compare', { params: { chains } }),
  corridors: (sort) => api.get('/cross-chain/corridors', { params: { sort_by: sort } }),
  corridor: (source, target) => api.get(`/cross-chain/corridors/${source}/${target}`),
  flow: (hours) => api.get('/cross-chain/flow', { params: { hours } }),
  volumeTrend: (days) => api.get('/cross-chain/trends/volume', { params: { days } }),
  tokenDistribution: () => api.get('/cross-chain/tokens/distribution'),
  startMonitoring: (interval) => api.post('/cross-chain/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/cross-chain/monitoring/stop'),
  monitoringStatus: () => api.get('/cross-chain/monitoring/status'),
};
