import api from './api';
export default {
  dashboard: () => api.get('/docs/dashboard'),
  list: (params) => api.get('/docs/', { params }),
  search: (q) => api.get('/docs/search', { params: { q } }),
  get: (id) => api.get(`/docs/${id}`),
  create: (data) => api.post('/docs/', data),
  update: (id, data) => api.patch(`/docs/${id}`, data),
  delete: (id) => api.delete(`/docs/${id}`),
  manifests: (params) => api.get('/docs/manifests', { params }),
  getManifest: (id) => api.get(`/docs/manifests/${id}`),
  createManifest: (data) => api.post('/docs/manifests', data),
  faqs: (params) => api.get('/docs/faqs', { params }),
  searchFaqs: (q) => api.get('/docs/faqs/search', { params: { q } }),
  createFaq: (data) => api.post('/docs/faqs', data),
  markHelpful: (id) => api.post(`/docs/faqs/${id}/helpful`),
  runbooks: (params) => api.get('/docs/runbooks', { params }),
  getRunbook: (id) => api.get(`/docs/runbooks/${id}`),
  createRunbook: (data) => api.post('/docs/runbooks', data),
};
