import api from './api';
export default {
  dashboard: () => api.get('/enhanced-security/dashboard'),
  audit: (params) => api.get('/enhanced-security/audit', { params }),
  auditSummary: () => api.get('/enhanced-security/audit/summary'),
  getAuditItem: (id) => api.get(`/enhanced-security/audit/${id}`),
  updateAuditItem: (id, data) => api.patch(`/enhanced-security/audit/${id}`, data),
  threats: (params) => api.get('/enhanced-security/threats', { params }),
  threatStats: () => api.get('/enhanced-security/threats/stats'),
  reportThreat: (data) => api.post('/enhanced-security/threats', data),
  updateThreat: (id, data) => api.patch(`/enhanced-security/threats/${id}`, data),
  blockedIps: () => api.get('/enhanced-security/threats/blocked-ips'),
  unblockIp: (ip) => api.delete(`/enhanced-security/threats/blocked-ips/${ip}`),
  ipScore: (ip) => api.get(`/enhanced-security/threats/ip-score/${ip}`),
  startMonitoring: () => api.post('/enhanced-security/monitoring/start'),
  stopMonitoring: () => api.post('/enhanced-security/monitoring/stop'),
  zkp: () => api.get('/enhanced-security/zkp'),
  createZkp: (data) => api.post('/enhanced-security/zkp', data),
  verifyZkp: (id, secret) => api.post(`/enhanced-security/zkp/${id}/verify`, { secret }),
  mfa: () => api.get('/enhanced-security/mfa'),
  setupMfa: (data) => api.post('/enhanced-security/mfa', data),
  verifyMfa: (data) => api.post('/enhanced-security/mfa/verify', data),
  disableMfa: (addr) => api.delete(`/enhanced-security/mfa/${addr}`),
  encryption: () => api.get('/enhanced-security/encryption'),
  rotateKey: (component) => api.post(`/enhanced-security/encryption/${component}/rotate`),
};
