import api from './api';
export default {
  dashboard: () => api.get('/explorer/dashboard'),
  stats: () => api.get('/explorer/stats'),
  blocks: (params) => api.get('/explorer/blocks', { params }),
  latestBlocks: (limit) => api.get('/explorer/blocks/latest', { params: { limit } }),
  getBlock: (height) => api.get(`/explorer/blocks/${height}`),
  blockTransactions: (height, limit) => api.get(`/explorer/blocks/${height}/transactions`, { params: { limit } }),
  getBlockByHash: (hash) => api.get(`/explorer/blocks/hash/${hash}`),
  transactions: (params) => api.get('/explorer/transactions', { params }),
  getTransaction: (hash) => api.get(`/explorer/transactions/${hash}`),
  getAddress: (addr) => api.get(`/explorer/addresses/${addr}`),
  addressTransactions: (addr, params) => api.get(`/explorer/addresses/${addr}/transactions`, { params }),
  topAddresses: (params) => api.get('/explorer/addresses', { params }),
  contracts: (params) => api.get('/explorer/contracts', { params }),
  getContract: (addr) => api.get(`/explorer/contracts/${addr}`),
  logs: (params) => api.get('/explorer/logs', { params }),
  search: (query) => api.get('/explorer/search', { params: { query } }),
  startMonitoring: (interval) => api.post('/explorer/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/explorer/monitoring/stop'),
  monitoringStatus: () => api.get('/explorer/monitoring/status'),
};
