import api from './api';
export default {
  dashboard: () => api.get('/faucet/dashboard'),
  stats: () => api.get('/faucet/stats'),
  config: () => api.get('/faucet/config'),
  updateConfig: (data) => api.patch('/faucet/config', data),
  claim: (data) => api.post('/faucet/claim', data),
  captcha: () => api.post('/faucet/captcha'),
  verifyCaptcha: (id, answer) => api.post('/faucet/captcha/verify', null, { params: { captcha_id: id, answer } }),
  requests: (params) => api.get('/faucet/requests', { params }),
  getRequest: (id) => api.get(`/faucet/requests/${id}`),
  addressInfo: (addr) => api.get(`/faucet/address/${addr}`),
  pause: () => api.post('/faucet/pause'),
  resume: () => api.post('/faucet/resume'),
  refill: (amount) => api.post('/faucet/refill', null, { params: { amount } }),
  addWhitelist: (addr) => api.post(`/faucet/whitelist/${addr}`),
  removeWhitelist: (addr) => api.delete(`/faucet/whitelist/${addr}`),
  getWhitelist: () => api.get('/faucet/whitelist'),
  addBlacklist: (addr) => api.post(`/faucet/blacklist/${addr}`),
  removeBlacklist: (addr) => api.delete(`/faucet/blacklist/${addr}`),
  getBlacklist: () => api.get('/faucet/blacklist'),
  startMonitoring: (interval) => api.post('/faucet/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/faucet/monitoring/stop'),
  monitoringStatus: () => api.get('/faucet/monitoring/status'),
};
