import api from './api';
export default {
  dashboard: () => api.get('/gateway/dashboard'),
  keys: (status) => api.get('/gateway/keys', { params: { status } }),
  createKey: (data) => api.post('/gateway/keys', data),
  getKey: (id) => api.get(`/gateway/keys/${id}`),
  updateKey: (id, data) => api.patch(`/gateway/keys/${id}`, data),
  revokeKey: (id) => api.delete(`/gateway/keys/${id}`),
  validateKey: (key) => api.post('/gateway/keys/validate', null, { params: { api_key: key } }),
  routes: (status, service) => api.get('/gateway/routes', { params: { status, target_service: service } }),
  createRoute: (data) => api.post('/gateway/routes', data),
  getRoute: (id) => api.get(`/gateway/routes/${id}`),
  updateRoute: (id, data) => api.patch(`/gateway/routes/${id}`, data),
  deleteRoute: (id) => api.delete(`/gateway/routes/${id}`),
  matchRoute: (path, method) => api.get('/gateway/routes/match', { params: { path, method } }),
  checkRateLimit: (keyId) => api.get(`/gateway/rate-limit/check/${keyId}`),
  cacheStats: () => api.get('/gateway/cache/stats'),
  clearCache: (routeId) => api.delete('/gateway/cache', { params: { route_id: routeId } }),
  usage: (params) => api.get('/gateway/usage', { params }),
  usageStats: (hours) => api.get('/gateway/usage/stats', { params: { hours } }),
  circuits: () => api.get('/gateway/circuits'),
  getCircuit: (routeId) => api.get(`/gateway/circuits/${routeId}`),
  resetCircuit: (routeId) => api.post(`/gateway/circuits/${routeId}/reset`),
  health: () => api.get('/gateway/health'),
  serviceHealth: (service) => api.get(`/gateway/health/${service}`),
  startMonitoring: (interval) => api.post('/gateway/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/gateway/monitoring/stop'),
  monitoringStatus: () => api.get('/gateway/monitoring/status'),
};
