import api from './api';
export default {
  dashboard: () => api.get('/governance/dashboard'),
  createProposal: (data) => api.post('/governance/proposals', data),
  listProposals: (params) => api.get('/governance/proposals', { params }),
  getProposal: (id) => api.get(`/governance/proposals/${id}`),
  vote: (id, data) => api.post(`/governance/proposals/${id}/vote`, data),
  tally: (id) => api.get(`/governance/proposals/${id}/tally`),
  getVotes: (id) => api.get(`/governance/proposals/${id}/votes`),
  finalize: (id) => api.post(`/governance/proposals/${id}/finalize`),
  execute: (id, hash) => api.post(`/governance/proposals/${id}/execute`, null, { params: { execution_hash: hash } }),
  cancel: (id, canceller) => api.post(`/governance/proposals/${id}/cancel`, null, { params: { canceller } }),
  proposalStats: () => api.get('/governance/proposals/stats'),
  createTreasury: (data) => api.post('/governance/treasury', data),
  listTreasury: (params) => api.get('/governance/treasury', { params }),
  getTreasury: (id) => api.get(`/governance/treasury/${id}`),
  approveTreasury: (id, approver) => api.post(`/governance/treasury/${id}/approve`, null, { params: { approver } }),
  rejectTreasury: (id) => api.post(`/governance/treasury/${id}/reject`),
  disburse: (id, tx) => api.post(`/governance/treasury/${id}/disburse`, null, { params: { tx_hash: tx } }),
  treasuryBalance: () => api.get('/governance/treasury/balance'),
  treasuryStats: () => api.get('/governance/treasury/stats'),
  addCouncilMember: (data) => api.post('/governance/council/members', data),
  removeCouncilMember: (addr) => api.delete(`/governance/council/members/${addr}`),
  listCouncil: (active) => api.get('/governance/council/members', { params: { active_only: active } }),
  getCouncilMember: (addr) => api.get(`/governance/council/members/${addr}`),
  councilStats: () => api.get('/governance/council/stats'),
  proposalTypes: () => api.get('/governance/types/proposals'),
  voteTypes: () => api.get('/governance/types/votes'),
};
