import api from './api';
export default {
  getPrivacy: (did) => api.get(`/identity-privacy/settings/${did}`),
  updatePrivacy: (did, data) => api.patch(`/identity-privacy/settings/${did}`, data),
  allowVerifier: (did, vid) => api.post(`/identity-privacy/settings/${did}/allow/${vid}`),
  blockDID: (did, bid) => api.post(`/identity-privacy/settings/${did}/block/${bid}`),
  checkAccess: (target, requester) => api.get(`/identity-privacy/access/${target}/${requester}`),
  rotateKey: (did) => api.post(`/identity-privacy/key-rotate/${did}`),
  rotationHistory: (did) => api.get(`/identity-privacy/key-rotate/${did}/history`),
  setGuardians: (data) => api.post('/identity-privacy/guardians', data),
  getGuardians: (did) => api.get(`/identity-privacy/guardians/${did}`),
  requestRecovery: (data) => api.post('/identity-privacy/recovery/request', data),
  approveRecovery: (id, data) => api.post(`/identity-privacy/recovery/${id}/approve`, data),
  cancelRecovery: (id) => api.post(`/identity-privacy/recovery/${id}/cancel`),
  getRecovery: (id) => api.get(`/identity-privacy/recovery/${id}`),
  listRecoveries: (did) => api.get('/identity-privacy/recovery/list', { params: { did } }),
  createDelegation: (data) => api.post('/identity-privacy/delegation/create', data),
  revokeDelegation: (id) => api.post(`/identity-privacy/delegation/${id}/revoke`),
  getDelegation: (id) => api.get(`/identity-privacy/delegation/${id}`),
  listDelegations: (did) => api.get('/identity-privacy/delegations', { params: { did } }),
  checkDelegation: (d, dl, p) => api.get(`/identity-privacy/delegation/check/${d}/${dl}/${p}`),
  addRevocation: (id) => api.post(`/identity-privacy/revocation-registry/${id}`),
  checkRevocation: (id) => api.get(`/identity-privacy/revocation-registry/check/${id}`),
  revocationRegistry: () => api.get('/identity-privacy/revocation-registry'),
  createZKP: (data) => api.post('/identity-privacy/zkp/create', data),
  verifyZKP: (id) => api.get(`/identity-privacy/zkp/${id}/verify`),
  getZKP: (id) => api.get(`/identity-privacy/zkp/${id}`),
  listZKPs: (did) => api.get('/identity-privacy/zkp/list', { params: { did } }),
  stats: () => api.get('/identity-privacy/stats'),
};
