import api from './api';
export default {
  dashboard: () => api.get('/mobile/dashboard'),
  stats: () => api.get('/mobile/stats'),
  appConfig: (ver) => api.get('/mobile/app-config', { params: { app_version: ver } }),
  registerSession: (data) => api.post('/mobile/sessions', data),
  listSessions: (params) => api.get('/mobile/sessions', { params }),
  getSession: (id) => api.get(`/mobile/sessions/${id}`),
  updateSession: (id, data) => api.patch(`/mobile/sessions/${id}`, data),
  deactivateSession: (id) => api.delete(`/mobile/sessions/${id}`),
  walletSessions: (addr) => api.get(`/mobile/wallet/${addr}/sessions`),
  features: (ver) => api.get('/mobile/features', { params: { app_version: ver } }),
  getFeature: (key) => api.get(`/mobile/features/${key}`),
  toggleFeature: (sid, key, enabled) => api.post(`/mobile/sessions/${sid}/features/${key}`, null, { params: { enabled } }),
  quickActions: () => api.get('/mobile/quick-actions'),
  sync: (sid, data) => api.post(`/mobile/sessions/${sid}/sync`, data),
  syncHistory: (params) => api.get('/mobile/sync/history', { params }),
  sendNotification: (sid, data) => api.post(`/mobile/sessions/${sid}/notifications`, data),
  broadcastNotification: (addr, data) => api.post(`/mobile/wallet/${addr}/notify`, data),
  getNotifications: (sid, unread) => api.get(`/mobile/sessions/${sid}/notifications`, { params: { unread_only: unread } }),
  markRead: (sid, nid) => api.post(`/mobile/sessions/${sid}/notifications/${nid}/read`),
  markAllRead: (sid) => api.post(`/mobile/sessions/${sid}/notifications/read-all`),
  mobileDashboard: (sid) => api.get(`/mobile/sessions/${sid}/dashboard`),
  startMonitoring: (interval) => api.post('/mobile/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/mobile/monitoring/stop'),
  monitoringStatus: () => api.get('/mobile/monitoring/status'),
};
