import api from './api';
export default {
  dashboard: () => api.get('/nft/dashboard'),
  stats: () => api.get('/nft/stats'),
  collections: (params) => api.get('/nft/collections', { params }),
  createCollection: (data) => api.post('/nft/collections', data),
  getCollection: (id) => api.get(`/nft/collections/${id}`),
  collectionStats: (id) => api.get(`/nft/collections/${id}/stats`),
  mint: (data) => api.post('/nft/mint', data),
  nfts: (params) => api.get('/nft/nfts', { params }),
  getNft: (id) => api.get(`/nft/nfts/${id}`),
  createListing: (data) => api.post('/nft/listings', data),
  listings: (params) => api.get('/nft/listings', { params }),
  getListing: (id) => api.get(`/nft/listings/${id}`),
  cancelListing: (id) => api.delete(`/nft/listings/${id}`),
  buyNft: (id, buyer) => api.post(`/nft/listings/${id}/buy`, null, { params: { buyer } }),
  viewListing: (id) => api.post(`/nft/listings/${id}/view`),
  placeBid: (id, data) => api.post(`/nft/listings/${id}/bids`, data),
  listBids: (id) => api.get(`/nft/listings/${id}/bids`),
  endAuction: (id) => api.post(`/nft/listings/${id}/end-auction`),
  transferNft: (id, from, to) => api.post(`/nft/nfts/${id}/transfer`, null, { params: { from_address: from, to_address: to } }),
  transfers: (params) => api.get('/nft/transfers', { params }),
  toggleFavorite: (nftId, user) => api.post(`/nft/favorites/${nftId}`, null, { params: { user } }),
  getFavorites: (user) => api.get('/nft/favorites', { params: { user } }),
  startMonitoring: (interval) => api.post('/nft/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/nft/monitoring/stop'),
  monitoringStatus: () => api.get('/nft/monitoring/status'),
};
