import api from './api';
export default {
  dashboard: () => api.get('/plugins/dashboard'),
  stats: () => api.get('/plugins/stats'),
  list: (params) => api.get('/plugins', { params }),
  get: (id) => api.get(`/plugins/${id}`),
  getBySlug: (slug) => api.get(`/plugins/slug/${slug}`),
  submit: (data) => api.post('/plugins/', data),
  update: (id, data) => api.patch(`/plugins/${id}`, data),
  approve: (id) => api.post(`/plugins/${id}/approve`),
  reject: (id, reason) => api.post(`/plugins/${id}/reject`, null, { params: { reason } }),
  suspend: (id) => api.post(`/plugins/${id}/suspend`),
  deprecate: (id) => api.post(`/plugins/${id}/deprecate`),
  install: (id, addr) => api.post(`/plugins/${id}/install`, null, { params: { user_address: addr } }),
  uninstall: (id, addr) => api.post(`/plugins/${id}/uninstall`, null, { params: { user_address: addr } }),
  installed: (addr) => api.get(`/plugins/installed/${addr}`),
  addReview: (id, data) => api.post(`/plugins/${id}/reviews`, data),
  getReviews: (id, limit) => api.get(`/plugins/${id}/reviews`, { params: { limit } }),
  markHelpful: (rid) => api.post(`/plugins/reviews/${rid}/helpful`),
  registerDeveloper: (data) => api.post('/plugins/developers', data),
  verifyDeveloper: (addr) => api.post(`/plugins/developers/${addr}/verify`),
  getDeveloper: (addr) => api.get(`/plugins/developers/${addr}`),
  listDevelopers: (verified) => api.get('/plugins/developers', { params: { verified_only: verified } }),
  categories: () => api.get('/plugins/categories/list'),
};
