import api from './api';
export default {
  dashboard: () => api.get('/readiness/dashboard'),
  securityScan: () => api.get('/readiness/security/scan'),
  findings: (params) => api.get('/readiness/findings', { params }),
  getFinding: (id) => api.get(`/readiness/findings/${id}`),
  addFinding: (data) => api.post('/readiness/findings', data),
  fixFinding: (id, notes) => api.post(`/readiness/findings/${id}/fix`, null, { params: { notes } }),
  acceptFinding: (id) => api.post(`/readiness/findings/${id}/accept`),
  checks: (params) => api.get('/readiness/checks', { params }),
  getCheck: (id) => api.get(`/readiness/checks/${id}`),
  updateCheck: (id, data) => api.patch(`/readiness/checks/${id}`, data),
  runAutoChecks: () => api.post('/readiness/checks/run-auto'),
  readinessScore: () => api.get('/readiness/score'),
  runLoadTest: (data) => api.post('/readiness/load-test', data),
  loadTests: (params) => api.get('/readiness/load-tests', { params }),
  getLoadTest: (id) => api.get(`/readiness/load-tests/${id}`),
  performanceSummary: () => api.get('/readiness/performance/summary'),
  checklist: (params) => api.get('/readiness/checklist', { params }),
  completeItem: (id, notes) => api.post(`/readiness/checklist/${id}/complete`, null, { params: { notes } }),
  resetItem: (id) => api.post(`/readiness/checklist/${id}/reset`),
  checklistProgress: () => api.get('/readiness/checklist/progress'),
  startMonitoring: (interval) => api.post('/readiness/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/readiness/monitoring/stop'),
  monitoringStatus: () => api.get('/readiness/monitoring/status'),
};
