import api from './api';
export default {
  dashboard: (addr) => api.get('/staking/dashboard', { params: { delegator: addr } }),
  networkStats: () => api.get('/staking/network/stats'),
  stake: (data) => api.post('/staking/stake', data),
  unstake: (id) => api.post(`/staking/positions/${id}/unstake`),
  withdraw: (id) => api.post(`/staking/positions/${id}/withdraw`),
  slash: (id, pct) => api.post(`/staking/positions/${id}/slash`, null, { params: { percentage: pct } }),
  toggleAutoCompound: (id) => api.post(`/staking/positions/${id}/auto-compound`),
  listPositions: (params) => api.get('/staking/positions', { params }),
  getPosition: (id) => api.get(`/staking/positions/${id}`),
  calculateRewards: (id) => api.get(`/staking/positions/${id}/rewards`),
  claimRewards: (id) => api.post(`/staking/positions/${id}/claim`),
  compoundRewards: (id) => api.post(`/staking/positions/${id}/compound`),
  listRewards: (addr, status) => api.get('/staking/rewards', { params: { delegator: addr, status } }),
  totalRewards: (addr) => api.get('/staking/rewards/total', { params: { delegator: addr } }),
  validators: (sort) => api.get('/staking/validators', { params: { sort_by: sort } }),
  getValidator: (id) => api.get(`/staking/validators/${id}`),
  calculate: (data) => api.post('/staking/calculate', data),
  history: (params) => api.get('/staking/history', { params }),
  userDashboard: (addr) => api.get(`/staking/user/${addr}`),
  startMonitoring: (interval) => api.post('/staking/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/staking/monitoring/stop'),
  monitoringStatus: () => api.get('/staking/monitoring/status'),
};
