import api from './api';
export default {
  dashboard: () => api.get('/tokenomics/dashboard'),
  supply: () => api.get('/tokenomics/supply'),
  allocations: () => api.get('/tokenomics/allocations'),
  allocation: (type) => api.get(`/tokenomics/allocations/${type}`),
  createVesting: (data) => api.post('/tokenomics/vesting', data),
  listVesting: (params) => api.get('/tokenomics/vesting', { params }),
  getVesting: (id) => api.get(`/tokenomics/vesting/${id}`),
  releaseVesting: (id) => api.post(`/tokenomics/vesting/${id}/release`),
  vestingStats: () => api.get('/tokenomics/vesting/stats'),
  recordFlow: (data) => api.post('/tokenomics/flows', data),
  listFlows: (params) => api.get('/tokenomics/flows', { params }),
  flowStats: () => api.get('/tokenomics/flows/stats'),
  utility: () => api.get('/tokenomics/utility'),
  updateUtility: (data) => api.patch('/tokenomics/utility', data),
  distributionChart: () => api.get('/tokenomics/distribution/chart'),
  supplyProgression: (months) => api.get('/tokenomics/supply/progression', { params: { months } }),
  flowTypes: () => api.get('/tokenomics/flow-types'),
};
