import api from './api';
export default {
  dashboard: () => api.get('/validators/dashboard'),
  stats: () => api.get('/validators/stats'),
  list: (params) => api.get('/validators', { params }),
  get: (id) => api.get(`/validators/${id}`),
  getByAddress: (addr) => api.get(`/validators/address/${addr}`),
  grade: (id) => api.get(`/validators/${id}/grade`),
  register: (data) => api.post('/validators/', data),
  pause: (id) => api.post(`/validators/${id}/pause`),
  activate: (id) => api.post(`/validators/${id}/activate`),
  slash: (id, reason) => api.post(`/validators/${id}/slash`, null, { params: { reason } }),
  remove: (id) => api.delete(`/validators/${id}`),
  updateGreenScore: (id, data) => api.patch(`/validators/${id}/green-score`, data),
  certify: (id) => api.post(`/validators/${id}/certify`),
  delegate: (data) => api.post('/validators/delegate', data),
  undelegate: (id) => api.post(`/validators/undelegate/${id}`),
  delegations: (params) => api.get('/validators/delegations', { params }),
  events: (id, limit) => api.get(`/validators/${id}/events`, { params: { limit } }),
  recentEvents: (limit) => api.get('/validators/events/recent', { params: { limit } }),
  startMonitoring: (interval) => api.post('/validators/monitoring/start', null, { params: { interval } }),
  stopMonitoring: () => api.post('/validators/monitoring/stop'),
  monitoringStatus: () => api.get('/validators/monitoring/status'),
};
